stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  before_script:
      - apt-get update --yes
      - apt-get install --yes libopenblas-dev cmake libclang-dev gfortran
      - rustc --version
  script:
    - cargo build -p softy -p implicits -p utils --verbose
    - cargo test -p softy -p implicits -p utils --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  before_script:
      - apt-get update --yes
      - apt-get install --yes libopenblas-dev cmake libclang-dev gfortran
      - rustc --version
  script:
    - cargo build -p softy -p implicits -p utils --verbose
    - cargo test -p softy -p implicits -p utils --verbose
  allow_failure: true
