[workspace]

members = [
    "utils",
    "hdkrs",
    "softy",
    "implicits",
    "implicits-c",
    "softy-hdk",
    "implicits-hdk",
    "vtkio-hdk",
]

[profile.release]
debug = false # Change this to true to enable debug symbols in release mode
