[package]
name = "softy"
version = "0.1.0"
authors = ["Egor Larionov <egor.larionov@gmail.com>"]

[dependencies]
nalgebra = "0.14"
ipopt = "0.1"
geometry-derive = { git = "ssh://git@gitlab.com/elrnv/geometry.git" }
geometry = { git = "ssh://git@gitlab.com/elrnv/geometry.git", features = ["io", "unstable"] }
rayon = "1.0"

[profile.release]
debug = true

[features]
unstable = []
