[package]
name = "softy"
version = "0.1.0"
authors = ["Egor Larionov <egor.larionov@gmail.com>"]

[dependencies]
nalgebra = "0.16"
ipopt = "0.1"
geometry-derive = { git = "ssh://git@gitlab.com/elrnv/geometry.git" }
geometry = { git = "ssh://git@gitlab.com/elrnv/geometry.git", features = ["io", "unstable"] }
rayon = "1.0"
reinterpret = "0.1"

[dev-dependencies]
criterion = { version = "0.2", features=['real_blackbox'] }

[profile.release]
debug = true

[features]
unstable = []

[[bench]]
name = "step_performance"
harness = false
