[workspace]

members = [
    "geo",
    "utils",
    "softy",
    "softy-hdk",
    "implicits",
    "cimplicits",
    "implicits-hdk",
    "benchmark",
]

[profile.release]
debug = true # Change this to true to enable debug symbols in release mode
rpath = false

[patch.crates-io]
autodiff = {git = "https://github.com/elrnv/autodiff.git"}
