[workspace]

members = [
    "geo",
    "utils",
    "hdkrs",
    "softy",
    "softy-hdk",
    "implicits",
    "cimplicits",
    "implicits-hdk",
    "vtkio-hdk",
]

exclude = [
    "utils/soap-derive",
]

[profile.release]
debug = false # Change this to true to enable debug symbols in release mode
rpath = false
