[package]
name = "sim-hdk"
version = "0.1.0"
authors = ["Egor Larionov <egor.larionov@gmail.com>"]

[lib]
name = "simhdk"
crate-type = ["cdylib", "rlib"]

[dependencies]
geometry = { git = "ssh://git@gitlab.com/elrnv/geometry.git" }
softy = { git = "ssh://git@gitlab.com/elrnv/softy.git" }
libc = "*"
hdkrs = { git = "ssh://git@gitlab.com/elrnv/hdkrs.git" }

[build-dependencies]
cbindgen = "0.4"
