[package]
name = "implicits-hdk"
version = "0.1.0"
authors = ["Egor Larionov <egor.larionov@gmail.com>"]

[lib]
name = "implicitshdk"
crate-type = ["cdylib", "rlib"]

[dependencies]
geometry = { git = "ssh://git@gitlab.com/elrnv/geometry.git" }
libc = "*"
implicits = { git = "ssh://git@gitlab.com/elrnv/implicits.git" }

[build-dependencies]
cbindgen = "0.6"
