[package]
name = "implicits"
version = "0.1.1"
authors = ["Egor Larionov <egor.larionov@gmail.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
rayon = "1.2"
na = { package = "nalgebra", version = "0.18" }
hrbf = "0.2"
geo = { package = "gut", path = "../../gut", features = ["io", "serde_all"] }
rstar = { version = "0.5" }
autodiff = "0.1"
reinterpret = "0.1"
num-traits = "0.2"
utils = { path = "../utils", features = ["autodiff"] }
serde = { version = "1.0", features = ["derive"], optional = true }
snafu = "0.5"
arrayvec = "0.5"

[dev-dependencies]
approx = "0.3"
rand = "0.5"
serde_json = "1.0"
criterion = "0.3"

[features]
unstable = ["criterion/real_blackbox"]
serde_all = ["serde", "rstar/serde"]

[[bench]]
name = "potential"
harness = false
