[package]
name = "utils"
version = "0.1.0"
authors = ["Egor Larionov <egor.larionov@gmail.com>"]
edition = "2018"

[dependencies]
geo = { package = "geometry", git = "ssh://git@gitlab.com/elrnv/geometry.git", features = ["io"] }
rand = "0.5"
cell = "0.1"
reinterpret = "0.1"

[dev-dependencies]
approx = "0.3"
