[package]
name = "implicits-hdk"
version = "0.1.1"
authors = ["Egor Larionov <egor.larionov@gmail.com>"]
edition = "2018"

[lib]
name = "implicitshdk"
crate-type = ["staticlib", "rlib"]

[dependencies]
geo = { package = "gut", version = "0.3" }
implicits = { path = "../implicits" }
hdkrs = { path = "../hdkrs" }

[build-dependencies]
cbindgen = "0.6"
