[package]
name = "softy"
version = "0.1.0"
authors = ["Egor Larionov <egor.larionov@gmail.com>"]
edition = "2018"

[dependencies]
na = { package = "nalgebra", version = "0.18" }
tensr = { git = "https://github.com/elrnv/tensr.git", features = ["autodiff"] }
flatk = { git = "https://github.com/elrnv/flatk.git", version = "0.3" }
ipopt = "0.5"
geo = { path = "../geo" }
rayon = "1.3"
reinterpret = "0.1"
implicits = { path = "../implicits" }
unroll = "0.1"
approx = "0.3"
num-traits = "0.2"
#jemallocator = "0.3"
image = "0.23" # For visualizing large sparse matrices
utils = { path = "../utils" }
is_sorted = "0.1"
sprs = "0.7.1"
sprs-ldl = "0.5.0"
ndarray = "0.13.1"
af = { package = "arrayfire", git = "https://github.com/elrnv/arrayfire-rust.git", optional = true }
thiserror = "1.0.16"
lazycell = "1.2"
log = "0.4"
hashbrown = "0.8"

[dev-dependencies]
criterion = "0.3"
autodiff = "0.2"
rand = "0.7"
env_logger = "0.8"

[features]
unstable = ["criterion/real_blackbox"]

[[bench]]
name = "box_stretch"
harness = false

[[bench]]
name = "box_squish"
harness = false

[[bench]]
name = "energy_hessian"
harness = false
