[package]
name = "softy"
version = "0.1.0"
authors = ["Egor Larionov <egor.larionov@gmail.com>"]
edition = "2018"

[dependencies]
na = { package = "nalgebra", version = "0.17" }
ipopt = { git = "ssh://git@gitlab.com/elrnv/ipopt-rs.git" }
geo = { package = "geometry", git = "ssh://git@gitlab.com/elrnv/geometry.git", features = ["io"] }
rayon = "1.0"
reinterpret = "0.1"
implicits = { path = "../implicits" }
#unroll = { git = "ssh://git@gitlab.com/elrnv/unroll.git" }
approx = "0.3"
num-traits = "0.2"
jemallocator = "0.3"
image = "0.21" # For visualizing large sparse matrices
utils = { path = "../utils" }
is_sorted = "0.1"

[dev-dependencies]
criterion = { version = "0.2" }
autodiff = "0.1"
rand = "0.5"

[features]
unstable = ["criterion/real_blackbox"]

[[bench]]
name = "step_performance"
harness = false
