[package]
name = "softy"
version = "0.1.0"
authors = ["Egor Larionov <egor.larionov@gmail.com>"]
edition = "2018"

[dependencies]
na = { package = "nalgebra", version = "0.18" }
ipopt = "0.5"
geo = { path = "../geo" }
rayon = "1.2"
reinterpret = "0.1"
implicits = { path = "../implicits" }
unroll = "0.1"
approx = "0.3"
num-traits = "0.2"
#jemallocator = "0.3"
image = "0.22" # For visualizing large sparse matrices
utils = { path = "../utils" }
is_sorted = "0.1"
sprs = "0.6.4"
sprs-ldl = "0.4.1"
ndarray = "0.12.1"
af = { package = "arrayfire", git = "https://github.com/elrnv/arrayfire-rust.git", optional = true }
snafu = "0.5"
lazycell = "1.2"
log = "0.4"

[dev-dependencies]
criterion = "0.3"
autodiff = "0.1"
rand = "0.5"
env_logger = "0.7"

[features]
unstable = ["criterion/real_blackbox"]

[[bench]]
name = "box_stretch"
harness = false

[[bench]]
name = "box_squish"
harness = false
