[package]
name = "softy-hdk"
version = "0.1.0"
authors = ["Egor Larionov <egor.larionov@gmail.com>"]
edition = "2018"

[lib]
name = "softyhdk"
crate-type = ["cdylib", "rlib"]

[dependencies]
geo = { package = "gut", version = "0.2" }
softy = { path = "../softy" }
libc = "*"
hdkrs = { path = "../hdkrs" }
lazy_static = "1.1"

[build-dependencies]
cbindgen = "0.6"
