name: softy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt -p softy -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install clippy
      run: rustup component add clippy
    - name: Run clippy
      run: cargo clippy -p softy
  test:
    name: Build and Test stable features
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, nightly]
        
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build -p softy --verbose
    - name: Test
      run: cargo test -p softy --verbose
